require('dotenv').config();

const AZURE_OPENAI_ENDPOINT = process.env['AZURE_OPENAI_ENDPOINT'];
const AZURE_OPENAI_API_KEY = process.env['AZURE_OPENAI_API_KEY'];
const AZURE_OPENAI_API_VERSION = process.env['AZURE_OPENAI_API_VERSION'];
const AZURE_COGNITIVE_API_VERSION = process.env['AZURE_COGNITIVE_API_VERSION'];
const AZURE_OPENAI_DEPLOYMENT = process.env['AZURE_OPENAI_DEPLOYMENT'];
const AZURE_COGNITIVE_SEARCH_API_KEY = process.env['AZURE_COGNITIVE_SEARCH_API_KEY'];
const AZURE_SEARCH_SERVICE_NAME = process.env['AZURE_SEARCH_SERVICE_NAME'];
const AZURE_SEARCH_INDEX_NAME = process.env['AZURE_SEARCH_INDEX_NAME'];
const AI_MODEL_MAX_TOKEN = 3000;
const AI_MODEL_TEMPERATURE = 0.7;
const AI_MODEL_TOP_P = 0.95;
const AI_MODEL_FREQUENCY_PENALTY = 0;
const AI_MODEL_PRESENCE_PENALTY = 0;
const AZURE_AI_SEARCH_ENDPOINT = process.env['AZURE_AI_SEARCH_ENDPOINT'];
const AZURE_OPENAI_DEPLOYMENT_ID = process.env['AZURE_OPENAI_DEPLOYMENT_ID'];
const AZURE_API_KEY = process.env['AZURE_API_KEY'];
const AZURE_STORAGE_CONNECTION_STRING = process.env['AZURE_STORAGE_CONNECTION_STRING'];
const CONTAINER_NAME = process.env['CONTAINER_NAME'];

module.exports = {
  AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_API_KEY,
  AZURE_OPENAI_API_VERSION,
  AZURE_OPENAI_DEPLOYMENT,
  AZURE_COGNITIVE_SEARCH_API_KEY,
  AZURE_SEARCH_SERVICE_NAME,
  AZURE_SEARCH_INDEX_NAME,
  AZURE_COGNITIVE_API_VERSION,
  AI_MODEL_MAX_TOKEN,
  AI_MODEL_TEMPERATURE,
  AI_MODEL_TOP_P,
  AI_MODEL_FREQUENCY_PENALTY,
  AI_MODEL_PRESENCE_PENALTY,
  AZURE_AI_SEARCH_ENDPOINT,
  AZURE_OPENAI_DEPLOYMENT_ID,
  AZURE_API_KEY,
  CONTAINER_NAME,
  AZURE_STORAGE_CONNECTION_STRING,
};
